version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg@arquibancada-app
      - POSTGRES_DB=arquibancada-app
    volumes:
      - pg:/var/lib/postgresql

  db-test:
    image: postgres
    ports: 
      - 5433:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test@arquibancadaapp
      - POSTGRES_DB=arquibancada-app
    volumes:
    - pg-test:/var/lib/postgresqltest
volumes:
  pg:
    driver: local
  pg-test:
    driver: local
