version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root@arquibancada-app
      - POSTGRES_DB=arquibancada-app
    volumes:
      - pg:/var/lib/postgresql

volumes:
  pg:
    driver: local
